language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
sudo: false
before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "nightly" ]] && [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then phpenv config-rm xdebug.ini; fi;
before_script:
  - ( if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php -d always_populate_raw_post_data=-1 -S 127.0.0.1:8000 tests/Server.php; fi; ) &
  - sleep 4
install:
  - composer install
script:
  - vendor/bin/phpunit
